---
- hosts: keras
  become: true
  tasks:
    - name: Install nvidia driver
      apt:
        name: nvidia-384
        update_cache: yes
    - name: Copy rc.local
      copy:
        src: rc.local
        dest: /etc/rc.local
        mode: 0755
    - name: Add nvidia key
      apt_key:
        url: http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64/7fa2af80.pub
    - name: Install nvidia repos
      apt:
        deb: "{{ item }}"
      with_items:
        - http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64/cuda-repo-ubuntu1604_9.2.148-1_amd64.deb
        - http://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1604/x86_64/nvidia-machine-learning-repo-ubuntu1604_1.0.0-1_amd64.deb
        - http://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1604/x86_64/nvinfer-runtime-trt-repo-ubuntu1604-4.0.1-ga-cuda9.0_1-1_amd64.deb
    - name: Install nvidia CUDA, cuDNN, CUPTI, NCCL, TensorRT
      apt:
        name: "{{ item }}"
        update_cache: yes
      with_items:
        - cuda-command-line-tools-9-0
        - cuda-cublas-9-0
        - cuda-cufft-9-0
        - cuda-curand-9-0
        - cuda-cusolver-9-0
        - cuda-cusparse-9-0
        - libcudnn7=7.2.1.38-1+cuda9.0
        - libnccl2=2.2.13-1+cuda9.0
        - libnvinfer4=4.1.2-1+cuda9.0
    - name: Install python3-pip
      apt:
        name: python3-pip
    - name: Install TensorFlow, Keras
      pip:
        name: "{{ item }}" 
      with_items:
        - tensorflow-gpu
        - keras
    - name: Download Keras MNIST CNN
      get_url:
        url: https://raw.githubusercontent.com/keras-team/keras/master/examples/mnist_cnn.py
        dest: /home/ubuntu/mnist_cnn.py
        mode: 0644
        owner: ubuntu
        group: ubuntu
